language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet restore src
 - dotnet publish src/rpi-garage-door.csproj -o build_out
 - cd build_out
 - zip build.zip
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build_out/build.zip
  skip_cleanup: true
